<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="unittest.loader.ModuleImportFailure-20180713175127" tests="1" time="0.000">
	<testcase classname="unittest.loader.ModuleImportFailure" name="test_1" time="0.000">
		<error message="Failed to import test module: test_1
Traceback (most recent call last):
  File &quot;E:\Automation\Python2\lib\unittest\loader.py&quot;, line 254, in _find_tests
    module = self._get_module_from_name(name)
  File &quot;E:\Automation\Python2\lib\unittest\loader.py&quot;, line 232, in _get_module_from_name
    __import__(name)
  File &quot;E:\Automation\GitKu\API_AutoTest\testcase\test_1.py&quot;, line 18
    def setUp(self):
      ^
IndentationError: expected an indented block
" type="ImportError">
<![CDATA[ImportError: Failed to import test module: test_1
Traceback (most recent call last):
  File "E:\Automation\Python2\lib\unittest\loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "E:\Automation\Python2\lib\unittest\loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "E:\Automation\GitKu\API_AutoTest\testcase\test_1.py", line 18
    def setUp(self):
      ^
IndentationError: expected an indented block

]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
